project:
  type: book
  output-dir: docs
book:
  title: "Metodologia da Transitividade Aplicada nas Escolas do Ensino Médio (E-book)"
  subtitle: "Guia Prático Para Produção de Vídeos Documentais"
  author:
    - name: João Batista Figueiredo Veiga
      orcid: 0000-0001-7262-3336
      corresponding: true
      affiliation:
        name: Professor de Sociologia - SEDUC/PA
      email: joao.veiga@detran.pa.gov.br
  date: "2025-08-21"
  cover-image: fig11.jpg
  favicon: capa1.jpg
  repo-url: https://github.com/Veiga1972
  repo-subdir: book
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [linkedin]
  downloads: [pdf, docx]
  page-navigation: true
  reader-mode: true
  sidebar:
    search: true
  page-footer:
    left: "Was Written by (VEIGA, J.B.F - 2026)."
    right: "SEDUC-PA."
  chapters:
    - index.qmd
    - intro.qmd
    - cap1.qmd
    - cap2.qmd
    - cap3.qmd
    - cap4.qmd
    - cap5.qmd
    - cap6.qmd
    - references.qmd
bibliography: references.bib
format:
  html:
    toc-title: "SUMÁRIO"
    toc-location: right
    number-sections: true
    theme:
      light: cosmo
      dark: superhero
    code-fold: true
    code-tools: false
    code-link: true
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png
abstract: ""












